version: '3.7'

services:
  web:
    container_name: web-container
    build: ./mysite
    restart: always
    command: uwsgi --ini mysite_uwsgi.ini # python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:12.1
    volumes:
      - postgres_data:/usr/local/var/postgres/
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=Qwer12345^
      - POSTGRES_DB=blog
  nginx:
    container_name: nginx-container
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/static    
    ports:
    - 8080:8080 # 1337:80
    depends_on:
      - web
volumes:
  postgres_data:  
  static_volume:    